spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

integrations:
  alchemy:
    api-key: ${ALCHEMY_API_KEY}
  etherscan:
    api-key: ${ETHERSCAN_API_KEY}
  chainbase:
    api-key: ${CHAINBASE_API_KEY}
  dextools:
    api-key: ${DEXTOOLS_API_KEY}
  thegraph:
    server-url-v3: "https://gateway-arbitrum.network.thegraph.com/api/<key>/subgraphs/id/5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV"
    server-url-v2: "https://gateway-arbitrum.network.thegraph.com/api/<key>/subgraphs/id/A3Np3RQbaBA6oKJgiwDJeo5T3zrYfGHPWFYayMwtNDum"
